env:
  node: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.jsx', '.tsx']
      moduleDirectory: ['node_modules', '.']
rules:
  react/react-in-jsx-scope: off
  react/jsx-sort-props:
    - warn
    - ignoreCase: true
      shorthandLast: true
      multiline: first
      reservedFirst: true
  import/order:
    - warn
    - newlines-between: never
      alphabetize:
        order: asc
        orderImportKind: asc
        caseInsensitive: true
